// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@v0.14.0',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowStandard(
    stepRunnerConfigDir: 'cicd/ploigos-step-runner-config/',
    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-quarkus-mvn-jenkins-std-fruit',

    workflowServiceAccountName: 'ploigos-workflow-ref-quarkus-mvn-jenkins-std-fruit',

    workflowWorkersImagePullPolicy: 'Always',

    workflowWorkerImageDefault: 'ploigos/ploigos-ci-agent-jenkins:edge',
    workflowWorkerImageUnitTest: 'ploigos/ploigos-tool-maven:edge',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:edge',
    workflowWorkerImageStaticCodeAnalysis: 'ploigos/ploigos-tool-sonar:edge',
    workflowWorkerImagePushArtifacts: 'ploigos/ploigos-tool-maven:edge',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-containers:edge',
    workflowWorkerImageContainerImageStaticComplianceScan: 'ploigos/ploigos-tool-openscap:edge',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'ploigos/ploigos-tool-openscap:edge',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:edge',
    workflowWorkerImageValidateEnvironmentConfiguration: 'ploigos/ploigos-tool-config-lint:edge',
    workflowWorkerImageUAT: 'ploigos/ploigos-tool-maven:edge',

    stepRunnerUpdateLibrary: true,
    stepRunnerLibSourceUrl: 'git+https://github.com/rhtconsulting/tssc-python-package.git@feature/results-refactor'
)
