// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@v0.17.0',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowStandard(
    stepRunnerConfigDir: 'cicd/ploigos-step-runner-config/',
    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-quarkus-mvn-jenkins-std-fruit',

    workflowServiceAccountName: 'ploigos-workflow-ref-quarkus-mvn-jenkins-std-fruit',

    workflowWorkerImageDefault: 'ploigos/ploigos-ci-agent-jenkins:v0.16.0',
    workflowWorkerImageUnitTest: 'ploigos/ploigos-tool-maven:v0.16.0',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:v0.16.0',
    workflowWorkerImageStaticCodeAnalysis: 'ploigos/ploigos-tool-sonar:v0.16.0',
    workflowWorkerImagePushArtifacts: 'ploigos/ploigos-tool-maven:v0.16.0',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-containers:v0.16.0',
    workflowWorkerImageContainerImageStaticComplianceScan: 'ploigos/ploigos-tool-openscap:v0.16.0',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'ploigos/ploigos-tool-openscap:v0.16.0',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:v0.16.0',
    workflowWorkerImageValidateEnvironmentConfiguration: 'ploigos/ploigos-tool-config-lint:v0.16.0',
    workflowWorkerImageUAT: 'ploigos/ploigos-tool-maven:v0.16.0'
)
